name: Tests

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libxkbcommon-dev libxinerama-dev libxcursor-dev
      - name: Configure
        run: cmake -B build .
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        working-directory: build
        run: ctest --output-on-failure

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        compiler: [mingw-w64, msvc]
        include:
          - compiler: mingw-w64
            platform_name: "MinGW Makefiles"
          - compiler: msvc
            platform_name: "Visual Studio 18 2026"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -G "${{ matrix.platform_name }}" -B build_${{ matrix.compiler }} .

      - name: Build
        run: cmake --build build_${{ matrix.compiler }} --config Release

      - name: Test (mingw-w64)
        run: build_${{ matrix.compiler }}\bin\raylib-lua-sol.exe tests/raylib-lua-sol-tests.lua
        if: matrix.compiler == 'mingw-w64'

      - name: Test (msvc)
        run: build_${{ matrix.compiler }}\bin\Release\raylib-lua-sol.exe tests/raylib-lua-sol-tests.lua
        if: matrix.compiler == 'msvc'
